version: '3.8'
services:
  app:
    container_name: education_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://admin:admin123@db:5432/education_db?schema=public
      - JWT_SECRET=your-secret-key-here
    depends_on:
      db:
        condition: service_healthy
    networks:
      - education_network

  db:
    container_name: education_db
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=education_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d education_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - education_network

volumes:
  postgres_data:
    name: education_db_data

networks:
  education_network:
    name: education_network 